apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: yougotthis4lyfe-tls
spec:
  secretName: yougotthis4lyfe-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: yougotthis4lyfe.com
  dnsNames:
    - yougotthis4lyfe.com
    - www.yougotthis4lyfe.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - yougotthis4lyfe.com
          - www.yougotthis4lyfe.com
